### PR TITLE
Feat blocklet capabilities

### PR DESCRIPTION
**Pull request by wangshijun**

### CODE REVIEW

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/abt-node/issues/448

**Review by NateRobinson — APPROVED** [review]
LGTM

**Comment by wangshijun** [comment]
@NateRobinson 这个依赖于 abtnode 仓库发版，暂时 hold，不要 merge

**Comment by wangshijun** [comment]
https://github.com/ArcBlock/abt-node/issues/587

**Pull request merged**
